### ISSUE TITLE
downscaling server side - not just for video

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2052]
When the client is using a `desktop-scaling` value lower than 1.0, we end up sending pixels that aren't all used client-side since we end up downscaling the picture to display it. (the render target is smaller than the picture the client receives)

It would be better if the client could tell the server about the scaling factor it is using then the server can:
* choose this same factor (or more) for video scaling - easy
* downscale picture data before compression: new capability flag, new client option, image down scaling pre-compression

**Comment by stdedos** [comment]
As-seen in https://github.com/Xpra-org/xpra/issues/2903#issuecomment-831769958, I can of course connect to the shadow server. Apart from the intermittent latency, jitter spikes and "pls wait" spinners, the shadowing works.

The original issue was problematic, and therefore the idea of this feature was to pre-scale the video, to reduce its size - because the vp[89] was unusable on Xenial (lack of codecs? IIRC). This change, however, was only valid in v4 (i.e. >Xenial).

So, I cannot expressively say that "this feature works and only this one solves the issue", since I don't know how to measure xpra's bandwidth pre/post of this feature, and the vp[89] may of course help (I have seen a lot of seamless rendering, and it uses the vp[89] codecs, the overall quality appears to be increased, **and** the overall lags/"pls wait" has dropped.

I can testify that "this feature did not break shadow" though 😛

**Comment by totaam** [comment]
Related fix for video scaling: a437a9eee1cb9790a02fc34e83d2fc3bc74eb901 (use the same ratio or a multiple thereof)

**Comment by totaam** [comment]
We now also downscale `jpeg` and `webp` using `libyuv`: b7647530b151640888f71e3c4e8c2499afd77bc3 - this could be improved: #3357
