### ISSUE TITLE
"Small windows" end up unrelated to window parent

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#2703]
*Issue migrated from trac ticket # 2703*

**component:** server | **priority:** minor

#### 2020-04-02 09:10:17: stdedos created the issue

___
> *Same looking ticket as #2697, but somewhat different*
> 
> With monitor layout [[Image(xpra_monitor-setup_ApplicationFrameHost_2020-04-02_10-50-02.png)]]
> 
> Small windows open outside of their parent. See the other attachment for explanation (it's too big to display here).
> 
> This happens for all sorts of actions (background indexing, Find !Action/File/Module/Find in Path), sometimes (sometimes they are closer to their original position, but not quite). Their original intent is to pop upwards/downwards (depending on window boundaries, e.g. for background indexing) of at window's center \(for the rest). Note that this centers the window (which starts as one toolbar with one textbox), according to its "maximum size", so that it won't look awkward when it's populated with results (1).
> 
> Also sometimes it happens that the small windows might open in-between monitor borders - I assume this is because you create the server as one big monitor, which is the bounding box of the monitors. Because Windows "think" they are maximized (#2643, #2651), the center-ish position (1) is at monitor's intersection.

**Comment by totaam** [comment]
Could very well be #3202 (fixed).

**Comment by stdedos** [comment]
Does not seem to fix the specified "Small window" (background task executer)
![Xpra_cmd_2021-07-27_13-05-14](https://user-images.githubusercontent.com/133706/127136426-66e9565f-9bd9-447d-8a3c-d0cc7bee765b.png)

**Comment by totaam** [comment]
5fd33c46d312bdd07d183d46cc0b29c17f3aaab1 and the refactoring for #3476 may help with this.

**Comment by stdedos** [comment]
I'll keep it in mind in future interactions; however, I think that this scenario is "indefinitely on hold" for me. 

Much more interesting to me "for the time being" is shadowing / "perfect scaling" - full screen / intercept all shortcuts (eg any WinKey shortcut), and basically "latency-free", "realtime" shadow on the same network (100Mbps eth over eth/wifi; rendering from the server "is troubled", even though actions are replicated instantaneously)

**Comment by totaam** [comment]
Is this still an issue with Xdummy and xpra v5?

**Comment by stdedos** [comment]
It "mostly works correctly", but there are corner cases:

![image](https://github.com/Xpra-org/xpra/assets/133706/9bbe4ddd-41f9-4de3-ae03-f549db5a3a2c)

I am not totally disappointed - apart from the few things, v5 looks solid.

**Comment by stdedos** [comment]
Same thing happens with the right-click menu items - I assume they are not "traditional" right-click menu items

![image](https://github.com/Xpra-org/xpra/assets/133706/fc7fe540-4929-4040-880c-d72fa321b9a2)

(the white-rendering is tracked in https://github.com/Xpra-org/xpra/issues/3989)

**Comment by totaam** [comment]
> It "mostly works correctly", but there are corner cases:

I have no idea what I am looking at. What is wrong here?

**Comment by stdedos** [comment]
The "Background tasks" window is "a child" to the smaller top-left window.

As Seamless has a "magic geometry" root window, here's an idea I had about it:

The "Background tasks" window, instead of being created .... idk, here

![image](https://github.com/Xpra-org/xpra/assets/133706/891aeba4-191d-4df1-b2a5-4a6db8694c2b)

(`window.bottom - 20px, window.right - 10px`), it instead "assumes" the root window to be a single display, and then it does `monitor.bottom - 20px, monitor.right - 10px`.

However, I also assume that Seamless display is a little bit like the red here

![image](https://github.com/Xpra-org/xpra/assets/133706/bceec675-0b03-4523-84fd-229575047852)

So, then, `monitor.bottom - 20px, monitor.right - 10px` (as red) makes sense why that small window lands _there_ instead of inside its seemingly-parent window.

But I'm happy to let this go if this is too complicated to grok and you have other priorities.

**Comment by totaam** [comment]
Probably the same resolution as this one:
https://github.com/Xpra-org/xpra/issues/3989#issuecomment-1707799223
This can only be fixed properly with Xdummy, which Debian is unable or unwilling to fix properly.

**Comment by totaam** [comment]
I'm going to close this as this is very likely a Debian-only issue.
