### ISSUE TITLE
Intermittent abort in xpra v4.0.6-r28351 client on fedora rawhide.

### ISSUE THREAD

**Issue by bittaurus** [Xpra-org/xpra#3012]
Just thought you guys should know that the client intermittently crashes for me while running in the background under fedora rawhide, since it will eventually become fc34.  It's not crucial for me, as I can always reconnect.

If you could use any other data on it, let me know.

[bug-report.zip](https://github.com/Xpra-org/xpra/files/5962159/bug-report.zip)

**Comment by totaam** [comment]
The Fedora packages are usually in very good shape since I use Fedora as my main OS.
I will be switching at least some of my machines to Fedora 34 shortly after the branch from rawhide.

When you say that "it crashes" but that you "can always reconnect". Do you mean that only the client crashes?
Is it a real crash or just a disconnection?
Do you have the command output when that happens? (assuming you run it from a terminal - and if not, please do so)
Or maybe a core file?
Can you get a GDB backtrace? (see https://github.com/Xpra-org/xpra/wiki/Debugging#gdb)

In the meantime, I see from your screenshot that you have nvenc enabled on a GTX 950M.
You may want to try disabling that to see if it helps: `--video-encoders=vpx,x264`.
(that's assuming that the client and server are on the same system or that this is a server crash, not a client crash)

**Comment by totaam** [comment]
This could be related to 9308043f8c32fbc08fc92a6d3349af29dd7b6d04 and #3039.

@bittaurus without further information, I have to close this ticket.
