### ISSUE TITLE
high cpu usage with speaker forwarding

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3020]
Reported on IRC about a CentOS 8 docker container.
_stracing that platform-python floods the terminal with_
```
recvmsg(7, 0x7ffd450caae0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
```
_it's maybe this in lsof_:
```
xpra    3749   272144    7u     sock    0,8      0t0 204146195 protocol: UNIX
```
Running with `--no-speaker` fixes the issue.
Perhaps the audio subprocess uses non-blocking reads on the pipes?
But this shows up as `sock`..
Needs checking.

**Comment by aki-k** [comment]
interestingly it only happens if i only use "--pulseaudio=no" and don't use the other two options 
"--speaker=no --microphone=no". it also doesn't happen if i don't use any of the three options.

the strace log was generated of about a 5 second period.

[xpra_pulseaudio_problem.txt](https://github.com/Xpra-org/xpra/files/5997632/xpra_pulseaudio_problem.txt)

**Comment by totaam** [comment]
We switched to `removesilence` in #3709.
I don't see anything here caused by xpra, this seems to be the result of the gstreamer pipeline.
I can copy the pipeline used:
```shell
xpra info | grep client.sound.speaker.pipeline
```
Then run it via `gst-launch-1.0` after replacing the `appsink` element with a `fakesink` and the resulting process shows the same behaviour.

So, closing as not-our-problem.
