### ISSUE TITLE
weird window geometry and mis-aligned mouse clicks for gnome-terminal

### ISSUE THREAD

**Issue by thomase00** [Xpra-org/xpra#3032]
I had been running xpra 1.x on RHEL 6.6 for a few years and recently upgraded to xpra 3.x on Centos 7.6 (my client has always been Windows 10). In the past on RHEL 6.6, border geometry for gnome-terminal was always a little weird on the right and bottom edge when maximized. This is because the app doesn't really support re-sizing to an arbitrary pixel width and height. Instead, the window appears to "snap" to a width and height that contains an integral number of vertical and horizontal characters. For example, for a non-maximized window, if you make it slightly taller, but not enough for another row of terminal characters, it will "snap" back to the previous height. Xpra always seemed to (and still does) do the correct thing when the window ISN'T maximized. However, it gets weird when the window is maximized, because the the pixel width and height of my screen does not fit an integral number of terminal characters. With xpra 1.x on RHEL 6.6, this was still basically ok. The effective window size would still effectively "snap" to an integral number of terminal characters, with the window "anchored" to the top-left of the drawable area (i.e. everything beneath the title bar), and the "extra" space along the right and bottom effectively blank (could be white, black, or transparent depending on the cirumstances). Although the right and bottom edges didn't necessary look pretty, the window functioned correctly.

Now with xpra 1.x on Centos 7.6, the behavior is different and I would say less desirable. I don't know if this a function of the newer version of gnome-terminal, or the newer version of xpra, or both. The entire contents of the window still "snaps" to an integral number of characters, but when it is maximized and there are inevitably extra pixels, and the window contents are effectively centered within a black border, rather than aligned to the top-left of the drawable area. This would be fine except for the fact that mouse click locations seem to still be registered with the assumption that the window is "anchored" to the top-left corner. For example, if I want to click-drag to highlight text, I now have to "aim" slightly above and to the left of the pixel location that I want to target in order to achieve the desired outcome.

**Comment by thomase00** [comment]
Actually, its not just gnome-terminal that does this. It is also happening in Xemacs, another app which snaps the window size to an integral number of characters.

**Comment by sto6** [comment]
I'll mention related symptoms, sorry not necessarily directly related or helpful (esp. since your client is Windows):

Using macos-client to view a remote-server's centos-6 desktop: Had to customize server's xorg.conf to change Virtual 8192 4096, to Virtual 1920 1080; else the display-size was wildly massive & apps often got DPI & fonts (e.g. tk scale) very wrong.

Had need to connect to same desktop from multiple client-monitors, some 1080p, others larger: If larger, I needed a fixed 1080p desktop top-left justified (with black space at bottom/right sides). Older macos-clients (pre gtk3) did it correctly, but newer instead centered the desktop (after you full-screen the client-viewer) with mouse-alignment failure like you mention.

Recently when viewing a remote-server's (now) centos-7 desktop, by more recent macos-clients (gtk3), if I still have that Virtual hack: I'm back in same boat: centered (failing mouse-alignments) instead of top-left justified. However here (centos-7, somewhat newer xpra-server than centos-6 I believe), the Virtual hack is unnecessary (the massive display-size & wrong DPI don't occur), and I don't need to force desktop always at 1080p (can allow desktop-resize).

In those cases: I suspect the centering (instead of top-left justified) with failed mouse-alignment is specific to the gtk3-based macos-clients, not being a server issue. And note that gtk3-clients have (for me) never respected auto desktop-fullscreen=yes on connect. Perhaps irrelevant, but I wondered if due to initial full-sceen attempt & fail the mouse-alignment damage is done, regardless if you manually full-screen thereafter.

**Comment by totaam** [comment]
None of these configurations are supported.
