### ISSUE TITLE
W: The repository 'https://xpra.org/beta xenial Release' does not have a Release file.

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3038]
Saddest message I received today:
```
W: The repository 'https://xpra.org/beta xenial Release' does not have a Release file.
E: Failed to fetch https://xpra.org/beta/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Xpra beta Xenial is dead. LONG LIVE THE XENIAL!

**Comment by totaam** [comment]
Ooops, I had wiped out the old beta packages since 4.1 came out, and I started uploading 4.2 to the beta folder.
But xenial doesn't get 4.x builds so the repository for xenial was now empty, and `dpkg-scanpackages` seems to be unhappy about that for some reason:
```
dpkg-scanpackages -m xenial/main/binary-amd64 > ./beta/xenial/main/binary-amd64/Packages
error scanning packages :1
```

The problem is that the build system has not been updated for git in older 3.x branches, so I can't make up to date builds for xenial yet...
So I just copied over the last stable build in there, and now `dpkg-scanpackages` is happy again..

**Comment by stdedos** [comment]
It seems that the webpage now contains files. However, especially coming up on Xenial's EOL, I thought you wouldn't bother - so I just disabled the repo altogether.
