### ISSUE TITLE
OBS GPU problem

### ISSUE THREAD

**Issue by emreanilterzioglu4dsight** [Xpra-org/xpra#3068]
Hi, I want to use multiple OBS session on remote server. I tried xpra it opens windows fine streaming fine but there is one problem. Problem is I checked use hardware decoding when available but it won't use GPU because of this my CPU percentage is too high. On the other side I select NVENC as encoder and while streaming hardware encoder working and I can see this process under nvidia-smi. I also use VLC media source but it is also not using hardware decoding. I think GPU work partially over xpra. 

Could you please help me?

**Comment by totaam** [comment]
> Problem is I checked use hardware decoding when available but it won't use GPU because of this my CPU percentage is too high

Where is this *use hardware decoding when available* option you speak of?
There is no such option in xpra and there is no hardware decoding support yet either.

**Comment by totaam** [comment]
Right, now I understand: you are complaining that your client applications running don't have access to the GPU when running in an xpra session.

That's because xpra uses a software only vfb to run your applications.
You can enable  `OpenGL` - which may solve your problems: https://github.com/Xpra-org/xpra/blob/master/docs/Usage/OpenGL.md
If that doesn't help, you may need to look into how these applications access the GPU and tweak your permissions / setup accordingly.

**Comment by emreanilterzioglu4dsight** [comment]
Hi @totaam, I tried these if I start as like below I can see the window on client side but again GPU not working.
` xpra start ssh://user@11.22.33.44/ --ssh="sudo ssh -i /media/pc/myfile.pem" --start="vglrun obs --collection user1 --profile user1 --multi"`

If I use below command Window does not show up on client side.
` xpra start ssh://user@11.22.33.44/ --ssh="sudo ssh -i /media/pc/myfile.pem" --start="obs --collection user1 --profile user1 --multi" --exec-wrapper="vglrun"`

I also tested with VLC instead of OBS and output is same and GPU not working.

**Comment by totaam** [comment]
> If I use below command Window does not show up on client side.

With versions prior to a340baca316e75fd361d51cf83660b637048a33a + 709959f567f3ffb6bd04dbfb7803e1d424cd1b1e, `exec-wrapper` needs to be an absolute path. ie: `-exec-wrapper=/usr/bin/vglrun`

As for allowing access to the GPU with your applications. You should figure out how they access it and for what purpose.  
In some cases, it may be possible to tell the application to use `OpenGL` instead of another backend (ie: `Xv` for video players) and then this may work using VirtualGL.  
In other cases, it may just be a permission issue, or you may be able to cheat and point to another `$DISPLAY`, etc..
