### ISSUE TITLE
Needs putty (plink) on Windows10, should use OpenSSH

### ISSUE THREAD

**Issue by psz2036** [Xpra-org/xpra#3113]
I find that xpra (client) on Windows10 needs plink from putty, does not
work well with the "built-in" C:/WINDOWS/System32/OpenSSH/ssh.exe .
Am I doing something wrong?

**Comment by totaam** [comment]
No, that's correct. That's why we ship with plink. And not just any plink but the plink from Tortoise SVN which includes better GUI dialogs.
For some reason, openssh doesn't work well when running as a subprocess on MS Windows and it does not provide any GUI for accepting keys or entering passphrases.
