### ISSUE TITLE
Issue with "smooth" scrolling

### ISSUE THREAD

**Issue by GbGp** [Xpra-org/xpra#3127]
Hi, I am using the xpra client under wayland and I am unable to scroll using the touchpad (two-fingers scrolling) or the trackpoint.
I can see that scrolling with any of the two generates GDK_SCROLL_SMOOTH events, but as far as I can see those are not handled in xpra. Any suggestion?

**Comment by totaam** [comment]
@GbGp you can try the commit above (trivial to apply) or wait for the 4.2 release.

Works-for-me on my laptop.

**Comment by GbGp** [comment]
works perfectly, thanks!

**Comment by totaam** [comment]
The problem is that normal scrolling events now come up as "smooth scroll" events, with the direction reversed.
And I can't see an easy way to differentiate between real smooth scroll events and the ones synthesized from regular scroll wheels.

So 41ba5af3197b24ea5fd8d482a4b3a5149c3647b3 inverts the Y direction.
The commit above also makes it possible to turn off smooth scrolling.
