### ISSUE TITLE
using attach and detach excessively causes overhead

### ISSUE THREAD

**Issue by Yonatan-Zaken** [Xpra-org/xpra#3180]
Using attach and detach excessively on a session causes a lot of
overhead which is reasonable since we are starting and closing an ssh
session each time.

Is there a way to perform an operation that "hides"  from the user the
application that is currently attached (exactly like when using detach),
without actually closing the ssh session, and of course perform a similar
operation that resumes the display of the attached application that was
previously "hidden" ?

**Comment by totaam** [comment]
We could quite easily add a _hide windows_ / _show_windows_ option in the tray menu.

But since this request comes from [this thread](https://lists.devloop.org.uk/pipermail/shifter-users/2021-June/002829.html), please be aware that there is ZERO chance of this feature ever making it into Ubuntu 14.04 as this version is no longer maintained.

**Comment by totaam** [comment]
Implemented in the commit above, this will be included in 4.3

**Comment by Yonatan-Zaken** [comment]
Thanks a-lot.
Even though I'm constrained to the older version im sure the functionality
will be useful.
