### ISSUE TITLE
xpra upgrade from r29386 to r29438 increased batch delay

### ISSUE THREAD

**Issue by stdedos** [Xpra-org/xpra#3206]
r29438 is 43c17cada941c28ce32b5ead4bb240eaf6463720

**Comment by stdedos** [comment]
r29406 (d03ead0e4) seems unaffected

**Comment by totaam** [comment]
r29406: is this at both ends? Just the client? If so, what's the server version?

**Comment by stdedos** [comment]
That's server.

Client (win10) is "stably" at r29346 (9096ffbb4)

**Comment by totaam** [comment]
The only commits that could affect latency within this range are:
* wifi device detection: d365728fc98ec8e5115e7a132d98611e6ac24da4 + 747a42f0051d16d1e96c98ef411e75d382e605c5 + 5b055a2aed3888fbbda00e2cf120f6b24ec04f7c. But your client is win10, not Linux.
* #3174 - but I think you are disabling most video codecs anyway, right?

The other possibility is that there is a difference in the builds themselves, with different codecs enabled in one and not the other.
But again, since you're disabling most video codecs. This should be obvious or just irrelevant.

**Comment by stdedos** [comment]
For both of the offered issues, it's a yes - I should be unaffected by them 😕

**Comment by stdedos** [comment]
In r29499 (27a2d4a97) delay spiked, but subsequently was reduced and stayed low 🤷
