### ISSUE TITLE
mouse focus different from keyboard focus

### ISSUE THREAD

**Issue by thomase00** [Xpra-org/xpra#3245]
At some point, the focus state of my session becomes "corrupted" such that clicking the mouse on a different window moves the keyboard focus to the new window, while the mouse focus remains on the original window. If I minimize the original window, mouse focus moves to the new window, but goes back to the original window when it is restored, even though keyboard focus remains with the new window. 

This issue persists even when I keep the Xorg session running and upgrade, or kill/restart with a new xpra session attached to the existing Xorg session. The only way to resolve the issue is to start a new session (including a new Xorg) entirely from scratch. I haven't been able to figure out what triggers this behavior because it is rare.

If I had to guess, I'd suspect that there is an X application behaving in an unexpected way which causes the session to go into an unexpected state.

Is there any workaround that I can use (either via xpra or Xorg), which will effectively reset the focus to a non-corrupted state so that I can recover the functionality of my session? 

I am using xpra version 3.0.13-r28351 on the server which is running Centos 7.6. My client is Windows 10.

**Comment by totaam** [comment]
Please first upgrade to xpra 3.0.14 which includes focus fixes.

Then when the problem occurs, please capture `xpra info`.

**Comment by thomase00** [comment]
It is kind of complicated for me to upgrade now that you don't support
Centos 7.6. I also don't have sudo. Historically, I have been downloading
all of the RPMs for my distribution, extracting the files manually, and
setting up my environment to use this "local" installation of xpra.

Now I don't see a Centos 7.6 distribution directory, but there is one for
7, which seems to be identical to 7.9. I have downloaded all the RPMs in
the Centos 7 distribution directory, using RPMs with "7" in the name rather
an "7_9" when available. The only ones that I might potentially need that
are only available with "7_9" are related to turbo jpeg.

Anyway, everything seems to be working fine, or at least as well as before
when I was running 3.0.13 downloaded from the Centos 7.6 distribution
directory (and I don't use audio, printing, or Linux client), except for 2
issues:

1.) CAPSLOCK no longer works. After toggling CAPSLOCK, my X applications
don't respond to keyboard input at all, not even control/alt/shift and
combinations. Everything works OK when I toggle it back off again.

2.) The VP8 and VP9 encoders are no longer available. I see that the
relevant python2 package files for vpx seems do be included in the
python2-xpra-3.0.13-10 RPM
(/usr/lib64/python2.7/site-packages/xpra/codecs/vpx), but they are missing
from python2-xpra-3.0.14-10 and later RPMs (I am using the RPMs for 3.1).
Was this left out on purpose, or moved someplace else?

Also, why are things basically working for me even though I'm using RPMs
that were effectively in the "7.9" distribution directory? As I said,
nearly all the RPMs that I have downloaded only have "7" in the name,
rather than "7_9". Does that mean that are compatible with any 7.x version?

**Comment by thomase00** [comment]
I figured out the keyboard problem in server_keyboard_config.py: (by using
"-d keyboard")

The do_get_keycode_new() function defined on line 519, doesn't take keystr
as an argument, despite it being used on line 531. I added the keystr
argument and passed it to the do_get_keycode_new() function on line 463.

**Comment by totaam** [comment]
> It is kind of complicated for me to upgrade now that you don't support Centos 7.6. I also don't have sudo.
> Historically, I have been downloading all of the RPMs for my distribution, extracting the files manually, and setting up my environment to use this "local" installation of xpra.

This should mostly work, just without any of the bits that do OS integration (mimetypes, printer forwarding, etc.)

> Now I don't see a Centos 7.6 distribution directory, but there is one for 7, which seems to be identical to 7.9.

Supporting every minor version was untenable. Only the current version of each branch is now supported, which at time of writing is 7.9 and 8.4

>  I have downloaded all the RPMs in the Centos 7 distribution directory, using RPMs with "7" in the name rather an "7_9" when available. 

The naming has only changed because of the way packages are now built.
https://github.com/Xpra-org/repo-build-scripts
Which means that "7" is generally what the new build system will produce.

> The only ones that I might potentially need that are only available with "7_9" are related to turbo jpeg.

https://github.com/Xpra-org/xpra/issues/2568

> Anyway, everything seems to be working fine, or at least as well as before when I was running 3.0.13 downloaded from the Centos 7.6 distribution directory (and I don't use audio, printing, or Linux client), except for 2 issues:
> 1.) CAPSLOCK no longer works. After toggling CAPSLOCK, my X applications don't respond to keyboard input at all, not even control/alt/shift and combinations. Everything works OK when I toggle it back off again.
> I figured out the keyboard problem in server_keyboard_config.py...

You mean like this? : e40c817dbc2f413cdf1478cc82eb43de04b3039e

> 2.) The VP8 and VP9 encoders are no longer available. I see that the relevant python2 package files for vpx seems do be included in the `python2-xpra-3.0.13-10` RPM (`/usr/lib64/python2.7/site-packages/xpra/codecs/vpx`), but they are missing from `python2-xpra-3.0.14-10` and later RPMs (I am using the RPMs for 3.1).

You are saying 3.1 and `python2-xpra-3.0.14-10` at the same time. Which is it?
This problem is related to the new build system and should be corrected in 3.1.1

> Was this left out on purpose, or moved someplace else?
> Also, why are things basically working for me even though I'm using RPMs that were effectively in the "7.9" distribution directory?
> As I said, nearly all the RPMs that I have downloaded only have "7" in the name, rather than "7_9".
> Does that mean that are compatible with any 7.x version?

No. You are just lucky enough that there weren't any major ABI breaks in between the version you are running (7.6) and the one this packages target (7.9).
Breakage was much more common earlier in the 7.x release cycle. (IIRC, 7.4 broke the X11 ABI)
Things may break at random. RedHat, and therefore CentOS, rebuild almost all packages for new releases to prevent such ABI issues.

**Comment by totaam** [comment]
> I'm saying that both the 3.0.14 and 3.1 versions of the python2-xpra package are not providing the vpx codec files.

OK, understood. 3.0.14 was also built using the new build system so that makes sense.
I think that the simple fix is already in 14cbfb3b89a676d2e6790e619f6fedbd0e1d60cb

> Regarding the 3.1.x branch, my understanding is that 4.x finally removes python2 compatibility, but the new 3.1.x branch, which is python2 compatible, got some backported features from 4.x and will continue to get bug fixes until 3.2.x where you will again backport features from 4.x.

Correct.
> If my understanding is correct, why ever move from python2 to python3 at all if there are so many systems out there still without python3 support?

I'm not sure I understand your point.
Just because CentOS 7 is stuck with python2 does not mean that every other distribution should continue to run with outdated libraries and versions.
The newer python3-only versions work a lot better than whatever I manage to backport to the 3.x branches and remain backwards compatible in every way.

> It seems like this makes it difficult to keep your software compatible with the maximum number of systems, many of which may be stuck on older OSes for various reasons.

I'm not aware of compatibility problems between xpra versions, whether they run on python2 or python3. That used to be a problem when 3.0 stabilized, but that's no longer the case.

**Comment by totaam** [comment]
Looks fixed to me, feel free to re-open if you still have problems.

> Now I don't see a Centos 7.6 distribution directory

The next release should have packages for CentOS 7.6 and later again: https://github.com/Xpra-org/repo-build-scripts/issues/4
Though you will need to point your repository file to the specific subdirectory you want to use.
