### ISSUE TITLE
x11-wm/xpra-4.2{,.1,.2}: Comment lines are deleted from ~/.ssh/known_hosts

### ISSUE THREAD

**Issue by holgersson32644** [Xpra-org/xpra#3266]
Hi,
if xpra connects to a yet unkown host it ask if the users wants to accept the server's key.
If the user accept, the whole ~/.ssh/known_hosts file is rewritten and all comment lines are stripped out. I tested versions xpra-4.2 to 4.2.2 on Gentoo with openssh-8.7_p1-r2.

Please fix this.

Kind reards,
Nils

**Comment by totaam** [comment]
This is not an xpra bug but a bug in paramiko.

In the default configuration, we rely on paramiko for implementing the ssh transport and call this function:
https://github.com/Xpra-org/xpra/blob/ed33f52737051efaba44ce5b22e9472153361155/xpra/net/ssh.py#L566-L567

The problem is that when paramiko loads the keys it just skips all the comments:
https://github.com/paramiko/paramiko/blob/33daa8e541cb91cdee01a085c368e1b388472e6a/paramiko/hostkeys.py#L98-L99

Please file a ticket there if you care: https://github.com/paramiko/paramiko or perhaps in this more active fork: https://github.com/ploxiln/paramiko-ng

**Comment by holgersson32644** [comment]
You're right, thanks for the detailed hints!

**Comment by holgersson32644** [comment]
I guess paramiko won't fix this, as there is already a five year old bug there :(

https://github.com/paramiko/paramiko/issues/680
