### ISSUE TITLE
AArch64/arm64 support?

### ISSUE THREAD

**Issue by jdstroy** [Xpra-org/xpra#3291]
Hello,

Would it be possible to build arm64 binary packages for Ubuntu 20.04?  I see that the advice is to avoid distribution packaging, but binaries aren't on xpra.org for arm64/aarch64.

Thanks.

**Comment by totaam** [comment]
I don't have any experience building arm packages on x86_64, I would prefer using buildah since that's what the [build scripts](https://github.com/Xpra-org/repo-build-scripts) already use, but it's not clear to me how feasible that is.
https://buildroot.org/ seems to be another popular option.

**Comment by totaam** [comment]
Doing a v3.1.x build today on a PI model B for #3288: this took over 3 hours before it failed at the very end! :angry: 
So I ended up doing some experimental beta builds on the PI4, which you can find here:
https://xpra.org/beta/buster/main/binary-armhf/
https://xpra.org/beta/buster/main/binary-arm64/

But I can't do this by hand for every release, for every sub-arch and for every distro...

---

I'm going to have to play with `buildah` and try to understand exactly what this does:
```shell
buildah from --arch arm64 --name "fedora-35-arm64-build" fedora:35
```

**Comment by jdstroy** [comment]
If it helps, Oracle Cloud has no-cost ARM servers available for the public.  They should be considerably faster than building on a Raspberry Pi.

    Linux jean 5.11.0-1016-oracle #17~20.04.1-Ubuntu SMP Thu Aug 12 06:20:07 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

```
processor       : 3
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1
```

**Comment by totaam** [comment]
It turns out that `buildah` does some magic and invokes `qemu-aarch64-static` when we create an `--arch arm64` image.
From then on, all the build scripts just work the same.
Emulation is not super-fast on my old i7 CPU, but it does seem to emulate multiple cores and this is a lot better than running on a RPI. The key thing is that it can be fully automated just like the other builds.

The build scripts updates are here:
https://github.com/Xpra-org/repo-build-scripts/commit/71f39e4495967925a13b2358e85b107fc6ff52c8

**Comment by jdstroy** [comment]
Awesome, thank you!  I'm looking forward to trying xpra-4.x.x on AArch64!

**Comment by totaam** [comment]
There are beta packages for:
* Ubuntu Focal
* Ubuntu Hirsute
* Debian Bullseye
* Fedora 34
in the beta area: https://xpra.org/beta/
The following distros should be coming later:
* Fedora 35
* CentOS / RHEL 8

This required a number of changes and fixes to the build scripts:
https://github.com/Xpra-org/repo-build-scripts/issues/3

@jdstroy / @rrthomas please let me know if those work for you so that I can close this ticket.

**Comment by rrthomas** [comment]
@totaam Sorry, I'm not sure why I subscribed to this issue! (I remember playing with xpra back in August, but that was to run Audacity conveniently via `run_scaled` on an x86_64 machine…)

**Comment by jdstroy** [comment]
Spectacular, thank you!  I've upgraded to Xpra 4.3 on Ubuntu 20.04 on AArch64 and now I have remote audio.

**Comment by totaam** [comment]
As of now, we produce arm64 packages for:
* Fedora 34 and 35
* CentOS 8
* Ubuntu focal and hirsute
* Debian bullseye

More can be added easily enough:
https://github.com/Xpra-org/repo-build-scripts

**Comment by totaam** [comment]
For CUDA support: #3378.

**Comment by totaam** [comment]
For the record, making `arm64` builds takes time, a lot of time. Even on powerful x86 hardware.
Building an updated `Cython` just took 23 hours.
