### ISSUE TITLE
Windows turn transparent when moved from Nvidia to Intel graphics

### ISSUE THREAD

**Issue by galexej** [Xpra-org/xpra#3449]
**Describe the bug**
I am using two graphics cards simultaneously on Windows for my various screens. Xpra works flawlessly on my main, external graphics (nvidia rtx 2080), but some applications have transparent elements on my secondary screens (intel uhd 630).

Yes, both of my graphics cards actually do something. My onboard card is not simply forwarding everything to the external card, but as soon as >50% of the window is on an onboard-connected screen, it is rendered by the onboard card.

Because it is kinda difficult to describe, I just filmed the entire issue to give an example. (In lack of proper screen recording software, I used my phone for this... apologies.)

https://www.youtube.com/watch?v=OpGz5xv4eqo

In that example, you can see three applications: Gedit (GTK), Putty (GTK) and KWrite (QT). As you can see, the problem is not specific to either GTK or QT, as both Putty and KWrite show the problem. However, some applications are fine - Gedit has no problem. I personally use Thunderbird, Firefox and various PDF viewers a lot, they all show no problems.

I am not using any special server or client options.

**To Reproduce**
1. Have a true dual-graphics card setup with intel-uhd-630 and nvidia-rtx-2080
2. Server command: `xpra start :100 --bind-tcp=localhost:12345`
3. Client command: `ssh -L 12345:localhost:26010 ...` (for port forwarding) and `Xpra.exe attach tcp:localhost:12345`
4. Drag a window to the intel-uhd-controlled screens. Some of them will be partly transparent.

**System Information (please complete the following information):**
 - Server OS: Arch Linux, Kernel 5.16.0
 - Client OS: Windows 10 Education Build 19044
 - Xpra Server Version: `v4.2.3-r3`
 - Xpra Client Version: `v4.3.1`

**Additional context**
- For some more information, please see the two attached images: (because `Xpra.exe info` shows nothing...)
  - [Software info screen](https://user-images.githubusercontent.com/1577623/151196803-9d4e9ca7-a8c8-4187-8681-b4b9bf3c8c45.png)
  - [Features info screen](https://user-images.githubusercontent.com/1577623/151196819-05196a68-5d37-47ca-898a-7942ef3b1f2c.png)
- [Server log](https://github.com/Xpra-org/xpra/files/7943258/xpra_server_log.txt)
- Disabling OpenGL fixes the issue, but the apps feel a little more laggy.
- According to the device manager, the NVIDIA driver version is 30.0.14.7196 (from 27.08.2021), and the Intel driver version is 25.20.100.6444 (from 19.11.2018), whatever this means.
- According to the Xpra session info, my server is using OpenGL 4.5, and the client is using 4.6 (see screenshots above). I assume this refers to the NVIDIA driver. I do not know how to display the Intel driver's OpenGL version though.
- [Possibly unrelated: Some apps are also more responsive than others. Thunderbird and Gedit are very responsive and it's fine to work with them, while in KWrite, most actions seem to be very delayed.]

I hope this has not already been reported. I was unable to find a similar issue in a quick search. If I forgot anything or I can give you any additional information, feel free to ask. :)

**Comment by totaam** [comment]
> Disabling OpenGL fixes the issue, but the apps feel a little more laggy.

That's expected.
Hopefully we can find a decent solution but I fear that the best we can do is to turn off opengl automatically when we detect this sort of setup because I don't think that we are going to be notified by the OS when the window is moved to another opengl renderer. Perhaps I am wrong.
You can try running with `-d opengl` and capture the smallest log sample possible when the window crosses over.

Otherwise, please post `xpra_cmd.exe opengl` from a cmd terminal window running on each display.

> while in KWrite, most actions seem to be very delayed

My guess is that kwrite is one of those applications that repaints the screen unnecessarily and / or uses transparency for nothing, and it probably ends up being throttled to compensate.
Having `xpra info` would tell us more.

**Comment by galexej** [comment]
Thank you for the reply!

- The command `xpra_cmd.exe opengl` shows the same on both screens. [xpra_cmd_opengl_nvidia.txt](https://github.com/Xpra-org/xpra/files/7943846/xpra_cmd_opengl_nvidia.txt)
- [xpra_info.txt](https://github.com/Xpra-org/xpra/files/7943936/xpra_info.txt)
- [xpra_-d_opengl.log](https://github.com/Xpra-org/xpra/files/7944163/xpra_-d_opengl.log) (it's only 2000 lines long...)
- I found a workaround for that bug, with OpenGL enabled:
  - Disable the primary screen.
  - Attach to the Xpra session with only the Intel-driven screens enabled.
  - [xpra_cmd_opengl_intel.txt](https://github.com/Xpra-org/xpra/files/7944113/xpra_cmd_opengl_intel.txt)
  - Re-enable the primary screen.
  - KWrite now displays correctly on both screems, and supposedly, OpenGL remains enabled.
  - (Shortly after that, I had a blue screen... but that is hopefully unrelated.)

**Comment by totaam** [comment]
So, from your logs, there is nothing unexpected when it comes to the opengl drivers:
* the nvidia comes up as:
```
renderer=NVIDIA GeForce RTX 2080/PCIe/SSE2
vendor=NVIDIA Corporation
```
* the intel one:
```
renderer=Intel(R) UHD Graphics 630
vendor=Intel
```

You captured `xpra info` without an active `kwrite` window, so that's no use!
(seen as: `windows.count=0`)

I can't skim through the client opengl debug log as it's too long.
The only part that looks suspicious is this one:
```
19:08:59,741 client   1 @17.436 GL do_configure_event(<Gdk.EventConfigure object at 0x000002222325dd10 (void at 0x000002221eef60b0)>)
19:08:59,741 client   1 @17.436 GL do_configure_event(<Gdk.EventConfigure object at 0x000002222325dcc0 (void at 0x000002221eea1bb0)>)
19:08:59,741 client   1 @17.436 draw_widget(<Gtk.DrawingArea object at 0x00000221dbeb9fc0 (GtkDrawingArea at 0x00000221d596e330)>, <cairo.Context object at 0x000002221e95c9f0>)
19:08:59,741 client   1 @17.436 wglMakeCurrent(0x3011074, 0x20000)
```
Followed by another one similar to that.
The window is probably being moved and we end up repainting it using the same opengl context.
It would probably be enough to just re-create the opengl context instead of calling `wglMakeCurrent`.
The difficulty is in detecting when this should be done.
Doing it after every series of `do_configure_event` is probably too much.

**Comment by totaam** [comment]
@galexej does it fix the issue if you click on "re-initialize windows" in the tray menu once a window has gone transparent?

**Comment by totaam** [comment]
I think that the commit above should fix your problem.
The opengl context re-initialization code works so well that I decided to enable this unconditionally - it can still be disabled with `XPRA_OPENGL_MONITOR_REINIT=0`.

You should now see a message like this one in your `xpra_cmd.exe` output whenever your windows are moved to a different monitor:
```
window 1 has been moved to monitor 1: DEL DP-0 3840x2160 at 0,0
```
And the opengl context will be re-created.
`-d opengl` should show a call to `wglCreateContext` soon after.

@galexej there are beta MS Windows builds with this change here: https://xpra.org/beta/windows/ (r30905 or later)
Does that fix things for you?

**Comment by galexej** [comment]
Hi @totaam! Thank you for all the effort you put into this issue! I'm sorry that I haven't responded earlier, weekdays are quite busy...

Sorry for the useless xpra_info - here is another one with open kwrite: [xpra_info.txt](https://github.com/Xpra-org/xpra/files/8002999/xpra_info.txt)

Re-initializing the windows does not fix the issue, it still appears transparent. Note that, in the xpra_cmd_opengl_only_intel.txt above, I initialized Xpra while only the secondary monitors were connected. This has been (so far) the only way that I could actually have anything being rendered by the Intel driver. I believe that, once Xpra initialized with the Nvidia driver, it sticks to it, no matter where the windows are located. But my expertise in that subject is very limited, ofc...

The beta client v4.4-r30905 did not help. When moving the window to the other monitor, it throws a bunch of errors and stops being rendered at all, until the windows are re-initialized manually again [which still makes it appear transparent]. Most of the errors (95%) just read:
```
2022-02-04 13:43:58,664 Error presenting FBO:
2022-02-04 13:43:58,664  GLError(
        err = 1282,
        description = b'Der Vorgang ist ung\xfcltig.',
        baseOperation = glEnd,
        cArguments = ()
)
```
Some of them include a stacktrace, with different starting points, but always ending in `File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError`. Full log so far: [xpra_glerror.txt](https://github.com/Xpra-org/xpra/files/8003549/xpra_glerror.txt)

I still believe that my workaround is worth checking further: I disabled all Nvidia-connected screens, started Xpra with only the Intel driver, re-enabled the Nvidia-screens, but Xpra remained on the Intel OpenGL version. With that, I have been able to move windows around without a problem.

Now here comes the part where I really don't know what I'm talking about: Is it possible to add an argument to Xpra where I can basically select the OpenGL version (instead of auto-detecting it)? Or would it be possible to basically print a list of all available OpenGL renderers, and then select a number (0 or 1) as an argument? Is this actually what the [:backends] parameter does in the --opengl argument? Until then, the screen-disable-technique is basically the way I start Xpra now and I can manage... :) Thanks again for all the effort!

**Comment by totaam** [comment]
> Re-initializing the windows does not fix the issue, it still appears transparent

Then I fear that it is not going to be possible to fix reliably because this means that MS Windows OpenGL doesn't pick a usable context / device, even when the window is created on the target GPU rather than moved there afterwards.

> When moving the window to the other monitor, it throws a bunch of errors and stops being rendered at all

I've reverted the default to not re-initialize the OpenGL context when moving windows to a new monitor.
I will have to test this on some real hardware running MS Windows, with NVidia and Intel iGPU - something which I do not have access to right now.

> Is it possible to add an argument to Xpra where I can basically select the OpenGL version (instead of auto-detecting it)?

You don't want to choose a version, you want to choose the GPU / OpenGL renderer.
The way this works at present is that we ask the MS Windows API (aka WGL) to give us an OpenGL window context for the given window handle using [wglCreateContext](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-wglcreatecontext):
https://github.com/Xpra-org/xpra/blob/b99351af9b0c53b7f2e32fd180f4418ed9feaddf/xpra/platform/win32/gl_context.py#L207-L210

What you would need is _GPU Affinity_. On MS Windows: [WGL_NV_gpu_affinity](https://www.khronos.org/registry/OpenGL/extensions/NV/WGL_NV_gpu_affinity.txt) for nvidia and [WGL_AMD_gpu_association](https://www.khronos.org/registry/OpenGL/extensions/AMD/WGL_AMD_gpu_association.txt) for AMD.

You haven't specified your GPU, but I am reading that the NVidia exension: _is only supported on QUADRO series_ ...

Then there's also `NvOptimusEnablement` - but I'm not sure that this would help here. (we want the opposite: use the Intel GPU, not the NVidia one)

**Comment by galexej** [comment]
A small update on the issue: my workaround suddenly no longer works. Instead, when I now try to run KWrite while Xpra initialized with the Intel OpenGL renderer, I get one out of memory error per second: [xpra_oom.txt](https://github.com/Xpra-org/xpra/files/8004507/xpra_oom.txt)
I don't know where the new issue came from. After all, I am happy that thunderbird works, which is the main reason why I am using Xpra right now. Whenever I need something else for a short time, it must simply be on the main screen.

**Comment by totaam** [comment]
> my workaround suddenly no longer works
> ..
> At least I switched back to version 4.3.2 before testing

That's the version you had before, is it not?
So something else has changed that is causing this problem.

**Comment by totaam** [comment]
Not heard back.
