### ISSUE TITLE
Xpra vs gnome-remote-desktop performance & bandwidth

### ISSUE THREAD

**Issue by TijZwa** [Xpra-org/xpra#3647]
During testing of gnome-remote-desktop we noticed that xpra consumes a lot less bandwidth compared to grd.
![image](https://user-images.githubusercontent.com/19667394/195269292-4b195058-efcf-4380-a861-93daaa4adc07.png)
We tested this on a local network. The performance of grd seems a lot better.
Scrolling was smoother and video playback was at the same speed as locally played video.

Xpra seemed slower; scrolling was not smooth and video was stuttering (a bit)
On a local network it wouldn't be a problem at all if Xpra uses all the bandwidth possible.

**Comment by TijZwa** [comment]
Perhaps Xpra is too aggressive with compression.
We need to look at CPU usage.
Lower CPU would means xpra is detecting better, high CPU would mean it is compressing more
(assuming the framerate and number of pixels is roughly the same)

**Comment by ndonkersloot** [comment]
I've tested the bandwith and will test the CPU usage at a later time.

**Comment by totaam** [comment]
Last time I really spent time on this, xpra was targeting ~10Mbps as minimum requirements, so perhaps we need to bump up this value.
Have you tried to see if you can increase the _smoothness_ of your session by raising the default `min-speed` value?
`speed` is the trade-off between the time / effort spent on compressing frames and bandwidth usage, by raising it you should use more bandwidth and may find the session to be more responsive.

**Comment by ndonkersloot** [comment]
I've tested again and have to say that the experience was a lot better this time, all tough i'm not sure what changed..
Below is a video file that demonstrates xpra (seamless mode) using some simple tasks and gnome-remote-desktop doing the same. There is a system monitor open so that CPU and bandwith usage is visible.

For some reason I keep getting random glitches with xpra in specific windows (save dialog libreoffice and firefox) that I don't have in gnome-remote-desktop. I can't get rid of them even after using different encoders. Any tips for tihs?

The xpra server was started using 'xpra start :10 --video-encoders=nvenc' The server has nvenc support (RTX3050 /w patched driver) and opengl support, although the client in the video doesn't use opengl in xpra due to using an Intel HD620 graphics card. Connection was made over ssh in a local network with a 1000mbit layer 2 link with an avarage of 0,2ms ICMP.

My experience is that the bandwith usage of xpra is much more erratic with high highs but also sudden lows.
I think this ultimately results in some unexpected stuttering that isn't the best user experience. We've tried raising the min speed value last time, but that didn't change much.

https://oc.vpo.nl/index.php/s/BSVSM84ewcsoXyH

**Comment by ndonkersloot** [comment]
> > `xpra start :10 --video-encoders=nvenc`
> 
> Never do that, it will result in stalls and many other problems. If `nvenc` is available, the server will use it whenever it is appropriate to do so.

Noted.

> > I keep getting random glitches with xpra in specific windows (save dialog libreoffice and firefox)
> 
> Please create a separate issue for this. What do you mean by "glitches"?

Will do. I mean the grey flickering that occurs in firefox.

> > the client in the video doesn't use opengl in xpra due to using an Intel HD620 graphics card
> 
> Did it end up being disabled automatically or did you disable opengl in the client yourself?

Automatically by the client because of this [blacklist](https://github.com/Xpra-org/xpra/blob/b5b792654a1c4aded135b0437ed771669a0e321d/xpra/client/gl/gl_drivers.py#L35).

> > My experience is that the bandwith usage of xpra is much more erratic with high highs but also sudden lows.
> 
> `-d compress` server output should tell us what is happening when the bandwidth usage is high, which may lead to a solution.

I've checked with debug logs enabled and encoding seems to switch between h264 and webp, also quality and speed seems to fluctuate a lot. I forced firefox to content-type video which resulted in much less encoding and quality/speed switching but experience wasn't smooth. I also tried to set min quality and min speed to high and low-latency which resulted in almost a fixed quality and speed value but bandwith remained very low around ~10mbit. Fluctuations were almost gone though.

> > I think this ultimately results in some unexpected stuttering that isn't the best user experience.
> 
> Yes, xpra tries to detect the bandwidth constraints and then allocate the bandwidth between each window to try to remain below this limit. In desktop mode, things are a lot easier since there is usually just one window / stream and the bandwidth can be managed much more simply.

I've also tried desktop mode and it is much less erratic, but response noticeable slower.

> > We've tried raising the min speed value last time, but that didn't change much.
> 
> This will increase the bandwidth usage and should lower latency by not spending much effort on compressing the pixel data.
> 
> > Below is a video file...
> 
> Had a quick look. This is probably the worst case scenario for testing xpra: by running youtube (almost) fullscreen, you end up with a session that resembles a full-desktop stream - which xpra has to detect (whereas a remote-desktop solution can just be lazy and use a video stream in all cases), then `--video-encoders=nvenc` will cause some stutters (don't do that), and when the page is scrolled then xpra has to detect that the video stream is no longer there, despite the fact that the same region of the screen is updating rapidly. Perhaps we can do better, but this is really the worst scenario you can come up with..

I'm sorry for bringing up such a worst case scenario :-), this one thing our users expect to work just fine though.

**Comment by totaam** [comment]
> Will do. I mean the grey flickering that occurs in firefox.

If you can give me steps to reproduce it then we can fix it.
It looks like a jpeg studio vs full range issue, or perhaps a colourspace subsampling issue.

> I've checked with debug logs enabled and encoding seems to switch between h264 and webp,

That's going to cost bandwidth. It may or may not be justified.
> also quality and speed seems to fluctuate a lot.

This may explain the switch to `webp`.
Video is normally sent at a lower quality value than the things around it.
> I forced firefox to content-type video which resulted in much less encoding and quality/speed switching but experience wasn't smooth.

Yes, browsers are special: video at times, text at other times.. tough!
> I also tried to set min quality and min speed to high and low-latency which resulted in almost a fixed quality and speed value but bandwith remained very low around ~10mbit. Fluctuations were almost gone though.

For video, the quality and speed difference are nowhere near as noticeable as with other types of content.

> I've also tried desktop mode and it is much less erratic, but response noticeable slower.

Do you mean the screen update latency? (even with a high `min-speed`?)

**Comment by totaam** [comment]
> Automatically by the client because of this blacklist

Have you tried force-enabling it with `--opengl=force` ?
This blacklist may well be out of date.

**Comment by ndonkersloot** [comment]
@totaam 
Thanks! That will help :+1: !
I've created an github issue #3658 regarding the glitches.

**Comment by TijZwa** [comment]
Talked to @ndonkersloot. Overall performance is now at the same level as gnome-remote-desktop. 
I will close the issue.
