### ISSUE TITLE
libavif v0.11.1 support?

### ISSUE THREAD

**Issue by AGI-chandler** [Xpra-org/xpra#3676]
Trying to install xpra on Debian testing but can't due to issues [enumerated here](https://tracker.debian.org/pkg/xpra).
So I've tried installing your version which is newer anyway, 4.4.1, but it wants old version 0.10.1 of libavif (libavif14), which isn't available for testing, but libavif15 is (0.11.1).  I modified the xpra deb so it depends on libavif15 instead, so I could at least install it, but I do get this expected error when running xpra:
```
 Error importing dec_avif (avif decoder)
 libavif.so.14: cannot open shared object file: No such file or directory
```
At least I got it installed and it otherwise runs fine, doing what I need for now,
Wondering, though, if this could somehow be worked on so there is more compatibility?
Thanks

**Comment by totaam** [comment]
As you found out, [don't use the downstream Debian packages](https://github.com/Xpra-org/xpra/wiki/Distribution-Packages).
As for `libavif.so.*`, we do not declare that dependency in the [control](https://github.com/Xpra-org/xpra/blob/master/packaging/debian/xpra/control) file so this dependency is automatic.
If you are running an unreleased distro (testing?) then this happens regularly as they break ABI with library updates - nothing we can do about it.
You should use the xpra's beta repository instead of the stable one until your distribution reaches stable, beta builds are made fairly regularly and will have the latest library every time.
