### ISSUE TITLE
Xpra configures xvfb with -dpi 96 instead of -dpi 96x96

### ISSUE THREAD

**Issue by eblanton** [Xpra-org/xpra#3716]
**Describe the bug**
Xpra v4.4.3-r0 is starting xvfb with `-dpi 96`, which causes xvfb on Ubuntu 20.04 (1.20.13-1ubuntu1~20.04.5) to start with a non-square DPI of 48x96, which is not ideal, and causes very small fonts.  Using `-dpi 96x96` fixes this.  This setting comes from `/etc/xpra/conf.d/55_server_x11.conf`.

I believe this should simply be changed to provide the full resolution, as `-dpi 96x96`.

**To Reproduce**
1. Start server with `xpra start`
2. Connect to server from any client
3. Check display DPI with `xdpyinfo`

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04.5 LTS
 - Client OS: Debian 11
 - Xpra Server Version v4.4.3-r0
 - Xpra Client Version 4.4.3-r0-1

**Comment by eblanton** [comment]
This does not appear to correctly identify the problem.  I am certainly seeing this:

```
screen #0:
  dimensions:    3840x1080 pixels (2032x286 millimeters)
  resolution:    48x96 dots per inch
```

However, no value of -dpi set in `/etc/xpra/conf.d` seems to change this if the server is started by the client using `xpra start ssh://hostname/`.  Running `xpra start :10` on the server starts a display with a square 96x96 DPI even with no configuration changes.  Running `xpra start --dpi 96 ssh://hostname/` starts a server with 96x96 DPI square pixels, as well.

I am leaving this bug open because something is not right, but the explanation in the initial post is not the issue.

**Comment by totaam** [comment]
I have applied the change to set `-dpi 96x96` since we don't support many distributions older than Ubuntu 20.04 so this switch is likely to be supported by all versions of `Xvfb` we care about.

The proper way of dealing with these DPI issues is to use Xdummy - which means avoiding Debian based distributions since they seem to be incapable of running it properly without errors or setup problems.

I am closing this issue because the `dpi` switch should not be used, should not be needed and `Xdummy` is the correct way of doing this.

**Comment by eblanton** [comment]
That ... is not helpful, and not within my ability to correct, but thank you for the clarification.
