### ISSUE TITLE
Xpra Start menu not responding (with html)

### ISSUE THREAD

**Issue by SkyperTHC** [Xpra-org/xpra#3753]
**Describe the bug**
Default Kali Linux install (ubuntu). 

```
xpra start --resize-display=1280x1024 --bind-tcp=127.0.0.1:2000,auth=allow -html=on --start=xterm --daemon=no
```

I can see my xterm (http://127.0.0.1:2000) and the XPRA/HTML background. There is s menu on the top left corner that shows "Start", "Server", "Information", ...

All the menu items work but not "Start". Hovering over "Start" with the mouse cursor or clicking on it and nothing happens (no menu opens).

xpra X11 seamless version 4.4.3-r0 64-bit
running with pid 1240 on Linux Kali 2022.4 kali-rolling

There is a test server to reproduce this:
```
ssh -L2000:0:2000 root@beta.segfault.net # password is 'segfault'
```

**Comment by totaam** [comment]
This usually means that the server does not provide the start menu data to the client.
Either because you started it with `--start-new-commands=no` or because it failed to parse the menu data.
Usually the latter on Ubuntu: https://github.com/Xpra-org/xpra/issues/2174#issuecomment-1294482319

If that's the case, please close this issue.

**Comment by SkyperTHC** [comment]
I had to do "pip install xdg" and then it worked.

Also, I added a script that enumerates all `/etc/xdg/menus/*-applications.menu' and sets `XDG_MENU_PREFIX=` to the latest match by file modification time.

Thanks for your great help.

btw, i tested various default installs on AWS, Digital Ocean, hetzner, ... and none of them sets XDG_MENU_PREFIX= in an SSH session. I understand that you are saying 'this is a problem of the distro' but the even if the distro might be at fault it's your users who are suffering :>   Perhaps it would be a clever idea to assist the user here and, if the value is not set, set it to the value from the newest file in /etc/xdg/menus (which is likely the one the user wants to use).

**Comment by totaam** [comment]
> and `pip install xdg` (wasnt installed).
> ...
> on Linux Kali 2022.4 kali-rolling

Then you should ask your packager to include the dependency - or perhaps they don't have a package for `python-xdg`?

> ... none of them sets XDG_MENU_PREFIX= in an SSH session

Not having it set is one thing, but then they should have a working default implementation so that this doesn't error out:
```shell
python -c "from xdg.Menu import parse;parse()"
```

Anyway, I've duplicated a large chunk of the `python-xdg` logic in a42e2343ee572ff2edb28ece0b38904969c75470 - does that work for you?
As for the ordering, I couldn't justify choosing the newest file, so I've left it to the glob and we use the first one that matches.
At least this allows users to easily specify the ordering: `01_my-applications.menu`, `02_another-applications.menu`...

**Comment by SkyperTHC** [comment]
awesome work. thanks.
