### ISSUE TITLE
more generic `command` for the exec authentication module

### ISSUE THREAD

**Issue by totaam** [Xpra-org/xpra#3790]
So that we can generate more useful commands based on the `username` specified:
https://github.com/Xpra-org/xpra/issues/3781#issuecomment-1461272502

Obviously, we want to be careful here and not allow just any string substitution as this would be ripe for exploitation.

**Comment by totaam** [comment]
It is now also possible to use the challenge (aka _password_) in the exec command:
```shell
xpra shadow -d auth --no-daemon \
    --bind-tcp=0.0.0.0:10000 \
    --tcp-auth=exec:require-challenge=yes,client-username=yes,command='touch /tmp/HELLO-${username}-${password}'  
```

Obviously, this should not be used with system passwords but this could be quite useful for delegating token validation to external command line tools.

**Comment by walakee** [comment]
@totaam, many thanks for this. Would these changes work in Xpra for CentOS 7.9? I was able to apply the deed568 changes to CentOS 7.9, but I'm not sure about this one.

Many thanks,
Walakee

**Comment by totaam** [comment]
@walakee no, this would be difficult to port - for a start, the authentication module interface has changed.

**Comment by walakee** [comment]
@totaam thanks for the immediate reply. Unfortunately CentOS Stream 8 seems to have an earlier EOL than CentOS 7.9. For this reason it is hard to justify the upgrade. Especially since it is not really a straight-forward process. Is there any workaround perhaps that could be used in CentOS 7.9 for the same purpose _(custom script to be executed after successful LDAP authentication, with username as the parameter)_?

Thanks again,
Walakee
