### ISSUE TITLE
xpra won't start (after update?)

### ISSUE THREAD

**Issue by angus73** [Xpra-org/xpra#4376]
**Describe the bug**
Maybe after some recent update (unfortunately I am not able to say if so, nor which one), my xpra doesn't work any more: on the client I see
`Error: failed to receive anything, not an xpra server?
   could also be the wrong protocol, username, password or port
   or the session was not found
`
and in the server I find
`
Xorg-for-Xpra-S42843: ../../../include/privates.h:121: dixGetPrivateAddr: Assertion 'key->initialized' failed.[...]
(EE) Please also check the log file at "/run/user/1000/xpra/S42843/Xorg.log" for additional information.
`

**To Reproduce**
1. server command
xpra start :666

2. client command
xpra attach ssh://myserver/666 --start=xterm

3. specific action to trigger the bug
the bug triggers without any specific action

**System Information (please complete the following information):**
 - Server OS: Fedora 39
 - Client OS: Ubuntu 22.04
 - Xpra Server Vesion 6.1.3-r0
 - Xpra Client Version 6.1.3-r0

I did try many ways to get this solved by myself, including removing xpra from both the client and the server, and also removing all files named *xpra* in the whole system, to have a clean configuration, but didn't help.

**Additional context**
I have two physical screens on the server, don't know if it can be related. It can be true that the problem appeared after I connected the second screen (on a second PCI display adapter, which I installed for the purpose), but I cannot be sure about that.

Many thanks in advance

[client.txt](https://github.com/user-attachments/files/17295093/client.txt)
[server.txt](https://github.com/user-attachments/files/17295095/server.txt)

**Comment by totaam** [comment]
> `Please also check the log file at "/run/user/1000/xpra/S42843/Xorg.log`

You probably won't find anything interesting there anyway. This is not an xpra error.

This is usually caused by driver or system updates messing up Xorg.
Rebooting usually fixes these issues.
Are applying more system updates.

**Comment by angus73** [comment]
Thanks, I tried again just after updating and rebooting both client and server and it still fails. Is there any hint I can follow? Do you think there's anything relevant in the attached logfiles, which I can use to go further in the right direction and ask for help to the right people, group, forum, etc? Many many thanks

**Comment by totaam** [comment]
> and rebooting both client and server and it still fails

This is a server problem.

> Is there any hint I can follow?

This could be caused by gstreamer so this may work:
https://github.com/Xpra-org/xpra/issues/3964#issuecomment-2126185895
Start your server with `--video-encoders=all,-gstreamer --video-decoders=all,-gstreamer` - though this should already be the default in 6.1.x
Or even removing the gstreamer bindings altogether.

---

This may be caused by: [dri2: Protect against dri2ClientPrivate assertion failures](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/1608) or [xorg-server-1.20.{7,8} crash with dixGetPrivateAddr: Assertion `key->initialized' failed when starting spice-gtk](https://gitlab.freedesktop.org/xorg/xserver/-/issues/1053)

---

By far, the easiest solution is to switch to Xvfb in https://github.com/Xpra-org/xpra/blob/eb3057cc40c0ef10e0bdbf3d4e3802f843936031/fs/etc/xpra/conf.d/55_server_x11.conf.in#L32

**Comment by angus73** [comment]
> By far, the easiest solution is to switch to Xvfb in
> 
> https://github.com/Xpra-org/xpra/blob/eb3057cc40c0ef10e0bdbf3d4e3802f843936031/fs/etc/xpra/conf.d/55_server_x11.conf.in#L32

That worked, thank you very much!
(Are there any drawbacks in it?)

**Comment by totaam** [comment]
> (Are there any drawbacks in it?)

Too many to list, some can be found here https://github.com/Xpra-org/xpra/blob/master/docs/Usage/Xdummy.md

**Comment by totaam** [comment]
FWIW: I've installed xpra latest stable (6.1.3 at time of writing) in a F39 VM and dummy worked out of the box - no need to switch to `Xvfb`.
So there must be something different on your system.
